"""The full acceptance scenario, start to finish, in the order specified.

Admin creates a site, a service and a Team Leader; that Team Leader files
evidence; the record is read-only; the admin can review it; a second Team
Leader cannot; the dashboards move.
"""
from __future__ import annotations

import re

from app.models import InstalledDevice, InstalledDeviceSite, MaintenanceRecord, ServiceType, Site, User
from tests.conftest import (
    ADMIN,
    CUSTOMER_B,
    csrf_of,
    ensure_service_quotation,
    login,
    logout,
    make_image,
)


def test_full_acceptance_workflow(client, db):
    # 1. The Administrator logs in.
    assert login(client, *ADMIN).status_code == 303
    assert client.get("/dashboard").status_code == 200

    admin_token = csrf_of(client, "/projects")

    # 2. The Administrator adds a new project.
    assert client.post(
        "/projects",
        data={
            "name": "Granada Business Park — Gate 1",
            "address": "Eastern Ring Road, Granada District",
            "city": "Riyadh",
            "contact_person": "Faisal Al-Otaibi",
            "contact_number": "+966 11 288 4400",
            "csrf_token": admin_token,
        },
    ).status_code == 303
    site = db.query(Site).filter(Site.name.like("Granada%")).one()

    # 3. The Administrator adds a service called "Camera Service".
    #    (One already exists from the fixture, so add a distinct one and verify both.)
    assert client.post(
        "/service-types",
        data={"name": "Gate Service", "description": "Barriers, motors and loop detectors",
              "csrf_token": admin_token},
    ).status_code == 303
    camera = db.query(ServiceType).filter(ServiceType.name == "Camera Service").one()
    assert camera.is_active is True

    # 4. The Administrator creates a Technical account.
    assert client.post(
        "/users",
        data={
            "full_name": "Omar Al-Rashid",
            "username": "omar@acceptance.local",
            "password": "Onsite@2026",
            "role": "technical",
            "phone": "+966 55 402 8811",
            "csrf_token": admin_token,
        },
    ).status_code == 303
    leader = db.query(User).filter(User.username == "omar@acceptance.local").one()
    assert leader.password_hash.startswith("$2")

    client.post("/logout", data={"csrf_token": admin_token})

    # 5. The Technical user logs in after completing maintenance at the site.
    assert login(client, "omar@acceptance.local", "Onsite@2026").status_code == 303

    form_page = client.get("/maintenance/submit")
    assert form_page.status_code == 200
    # 6/7. The new project and Camera Service are both offered.
    assert "Granada Business Park — Gate 1" in form_page.text
    assert "Camera Service" in form_page.text

    installed = InstalledDevice(
        site_id=site.id,
        device_id=1,
        customer_name=site.customer_name,
        site_name=site.name,
        device_name="IP Camera",
        manufacturer="Axis",
        device_model="P3265-LV",
        serial_number="ACCEPTANCE-SN-001",
    )
    installed.work_site_evidence = InstalledDeviceSite(site_id=1, site_name="Gate 1")
    db.add(installed)
    db.commit()

    csrf = re.search(r'name="csrf_token" value="([^"]+)"', form_page.text).group(1)
    form_token = re.search(r'name="form_token" value="([^"]+)"', form_page.text).group(1)

    # 8-13. Names, result, notes, issue, recommendations and a previewed photo.
    submission = client.post(
        "/maintenance/submit",
        data={
            "csrf_token": csrf,
            "form_token": form_token,
            "project_id": str(site.id),
            "quotation_number": ensure_service_quotation(site.id),
            "work_site_id": "1",
            "installed_device_id": str(installed.id),
            "service_type_id": str(camera.id),
                "participant_ids": ["2", "3"],
            "result": "completed_with_observations",
            "notes": "Cleaned all eight dome cameras, re-seated two BNC connectors and verified "
                     "seven days of playback on every channel.",
            "issue_description": "Camera 6 housing has a cracked gasket and water has entered the dome.",
            "recommendations": "Replace the camera 6 housing before the next rainy season.",
        },
        files=[("photos", ("camera6_dome.jpg", make_image(), "image/jpeg"))],
    )
    # 14. Submitted.
    assert submission.status_code == 303

    record = db.query(MaintenanceRecord).one()

    # 15. Record number generated by the backend.
    assert re.fullmatch(r"PM-\d{4}-\d{5}", record.record_number)
    # 16. Logged-in Technical user recorded.
    assert record.submitted_by_id == leader.id
    assert record.team_leader_name == "Omar Al-Rashid"
    # 17. Server-side submission timestamp.
    assert record.submitted_at is not None and record.created_at is not None

    # 18. The record opens as a controlled, auditable record.
    detail_url = submission.headers["location"]
    assert detail_url == f"/maintenance/records/{record.id}"
    detail = client.get(detail_url)
    assert detail.status_code == 200
    assert record.record_number in detail.text
    assert "Every change is recorded in the audit history" in detail.text
    assert "Edit record" in detail.text
    assert "Delete record" not in detail.text
    assert "Leader One" in detail.text and "Leader Two" in detail.text
    assert "cracked gasket" in detail.text

    # 19. The Technical user finds it in the full history.
    history = client.get("/maintenance/records")
    assert record.record_number in history.text

    leader_dashboard = client.get("/dashboard").text
    assert "All submitted field-service evidence" in leader_dashboard

    logout(client)

    # 21. Another Team Leader cannot reach the record or its photo.
    login(client, *CUSTOMER_B)
    assert client.get(detail_url).status_code == 403
    assert client.get(f"/media/photo/{record.photos[0].id}").status_code == 403
    assert record.record_number not in client.get("/maintenance/records").text
    logout(client)

    # 20. The Administrator reviews everything including the proof photo.
    login(client, *ADMIN)
    admin_view = client.get(detail_url)
    assert admin_view.status_code == 200
    assert "Omar Al-Rashid" in admin_view.text
    assert "Granada Business Park" in admin_view.text
    assert site.customer_name == site.name

    photo = client.get(f"/media/photo/{record.photos[0].id}")
    assert photo.status_code == 200
    assert photo.headers["content-type"] == "image/jpeg"
    assert client.get(f"/media/photo/{record.photos[0].id}?size=thumb").status_code == 200

    # 22. Dashboard statistics reflect the new record.
    admin_dashboard = client.get("/dashboard").text
    assert "Completed with observations" in admin_dashboard
    assert "Omar Al-Rashid" in admin_dashboard
    assert "Granada Business Park — Gate 1" in admin_dashboard
