"""initial schema

Revision ID: bc0a78bbcdf8
Revises: 
Create Date: 2026-07-29 12:37:51.175474

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc0a78bbcdf8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account_recovery_attempts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('identifier_hash', sa.String(length=64), nullable=False),
    sa.Column('ip_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_account_recovery_attempts_created_at'), 'account_recovery_attempts', ['created_at'], unique=False)
    op.create_index(op.f('ix_account_recovery_attempts_identifier_hash'), 'account_recovery_attempts', ['identifier_hash'], unique=False)
    op.create_index(op.f('ix_account_recovery_attempts_ip_hash'), 'account_recovery_attempts', ['ip_hash'], unique=False)
    op.create_table('device_catalog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('manufacturer', sa.String(length=120), nullable=True),
    sa.Column('model', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('length(trim(model)) > 0', name='ck_device_model_present'),
    sa.CheckConstraint('length(trim(name)) > 0', name='ck_device_name_present'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'model', name='uq_device_name_model')
    )
    op.create_index(op.f('ix_device_catalog_is_active'), 'device_catalog', ['is_active'], unique=False)
    op.create_index(op.f('ix_device_catalog_manufacturer'), 'device_catalog', ['manufacturer'], unique=False)
    op.create_index(op.f('ix_device_catalog_model'), 'device_catalog', ['model'], unique=False)
    op.create_index(op.f('ix_device_catalog_name'), 'device_catalog', ['name'], unique=False)
    op.create_table('general_maintenance_record_counters',
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('last_sequence', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('year')
    )
    op.create_table('installation_record_counters',
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('last_sequence', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('year')
    )
    op.create_table('record_counters',
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('last_sequence', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('year')
    )
    op.create_table('record_revisions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('record_type', sa.String(length=40), nullable=False),
    sa.Column('record_id', sa.Integer(), nullable=False),
    sa.Column('record_number', sa.String(length=20), nullable=False),
    sa.Column('action', sa.String(length=20), nullable=False),
    sa.Column('edited_by_id', sa.Integer(), nullable=False),
    sa.Column('editor_name', sa.String(length=120), nullable=False),
    sa.Column('changes_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_record_revisions_action'), 'record_revisions', ['action'], unique=False)
    op.create_index(op.f('ix_record_revisions_created_at'), 'record_revisions', ['created_at'], unique=False)
    op.create_index(op.f('ix_record_revisions_edited_by_id'), 'record_revisions', ['edited_by_id'], unique=False)
    op.create_index(op.f('ix_record_revisions_record_id'), 'record_revisions', ['record_id'], unique=False)
    op.create_index(op.f('ix_record_revisions_record_number'), 'record_revisions', ['record_number'], unique=False)
    op.create_index(op.f('ix_record_revisions_record_type'), 'record_revisions', ['record_type'], unique=False)
    op.create_table('service_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('length(trim(name)) > 0', name='ck_service_types_name_present'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_service_types_is_active'), 'service_types', ['is_active'], unique=False)
    op.create_index(op.f('ix_service_types_name'), 'service_types', ['name'], unique=True)
    op.create_table('sites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('customer_name', sa.String(length=160), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=False),
    sa.Column('city', sa.String(length=80), nullable=True),
    sa.Column('contact_person', sa.String(length=120), nullable=True),
    sa.Column('contact_number', sa.String(length=40), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('length(trim(name)) > 0', name='ck_sites_name_present'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'customer_name', name='uq_site_name_customer')
    )
    op.create_index(op.f('ix_sites_customer_name'), 'sites', ['customer_name'], unique=False)
    op.create_index(op.f('ix_sites_is_active'), 'sites', ['is_active'], unique=False)
    op.create_index(op.f('ix_sites_name'), 'sites', ['name'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=120), nullable=False),
    sa.Column('username', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('admin', 'technical', 'customer', name='userrole', native_enum=False, length=20), nullable=False),
    sa.Column('phone', sa.String(length=40), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('length(trim(full_name)) > 0', name='ck_users_full_name_present'),
    sa.CheckConstraint('length(trim(username)) > 0', name='ck_users_username_present'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_is_active'), 'users', ['is_active'], unique=False)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('work_sites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('length(trim(name)) > 0', name='ck_work_site_name_present'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_work_sites_is_active'), 'work_sites', ['is_active'], unique=False)
    op.create_index(op.f('ix_work_sites_name'), 'work_sites', ['name'], unique=True)
    op.create_table('account_recovery_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('purpose', sa.String(length=30), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_account_recovery_tokens_created_at'), 'account_recovery_tokens', ['created_at'], unique=False)
    op.create_index(op.f('ix_account_recovery_tokens_expires_at'), 'account_recovery_tokens', ['expires_at'], unique=False)
    op.create_index(op.f('ix_account_recovery_tokens_purpose'), 'account_recovery_tokens', ['purpose'], unique=False)
    op.create_index(op.f('ix_account_recovery_tokens_token_hash'), 'account_recovery_tokens', ['token_hash'], unique=True)
    op.create_index(op.f('ix_account_recovery_tokens_used_at'), 'account_recovery_tokens', ['used_at'], unique=False)
    op.create_index(op.f('ix_account_recovery_tokens_user_id'), 'account_recovery_tokens', ['user_id'], unique=False)
    op.create_table('admin_recovery_contacts',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('verified_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_admin_recovery_contacts_email'), 'admin_recovery_contacts', ['email'], unique=True)
    op.create_table('customer_project_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['sites.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'project_id', name='uq_customer_project_assignment')
    )
    op.create_index(op.f('ix_customer_project_assignments_project_id'), 'customer_project_assignments', ['project_id'], unique=False)
    op.create_index(op.f('ix_customer_project_assignments_user_id'), 'customer_project_assignments', ['user_id'], unique=False)
    op.create_table('general_maintenance_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('record_number', sa.String(length=20), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.Column('work_site_id', sa.Integer(), nullable=False),
    sa.Column('service_type_id', sa.Integer(), nullable=False),
    sa.Column('submitted_by_id', sa.Integer(), nullable=False),
    sa.Column('project_name', sa.String(length=160), nullable=False),
    sa.Column('site_name', sa.String(length=120), nullable=False),
    sa.Column('project_address', sa.String(length=255), nullable=False),
    sa.Column('service_name', sa.String(length=120), nullable=False),
    sa.Column('team_leader_name', sa.String(length=120), nullable=False),
    sa.Column('result', sa.Enum('completed_successfully', 'completed_with_observations', 'further_action_required', 'unable_to_complete', name='maintenanceresult', native_enum=False, length=40), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['service_type_id'], ['service_types.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['submitted_by_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['work_site_id'], ['work_sites.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_general_maintenance_records_project_name'), 'general_maintenance_records', ['project_name'], unique=False)
    op.create_index(op.f('ix_general_maintenance_records_record_number'), 'general_maintenance_records', ['record_number'], unique=True)
    op.create_index(op.f('ix_general_maintenance_records_result'), 'general_maintenance_records', ['result'], unique=False)
    op.create_index(op.f('ix_general_maintenance_records_service_name'), 'general_maintenance_records', ['service_name'], unique=False)
    op.create_index(op.f('ix_general_maintenance_records_service_type_id'), 'general_maintenance_records', ['service_type_id'], unique=False)
    op.create_index(op.f('ix_general_maintenance_records_site_id'), 'general_maintenance_records', ['site_id'], unique=False)
    op.create_index(op.f('ix_general_maintenance_records_site_name'), 'general_maintenance_records', ['site_name'], unique=False)
    op.create_index(op.f('ix_general_maintenance_records_submitted_at'), 'general_maintenance_records', ['submitted_at'], unique=False)
    op.create_index(op.f('ix_general_maintenance_records_submitted_by_id'), 'general_maintenance_records', ['submitted_by_id'], unique=False)
    op.create_index(op.f('ix_general_maintenance_records_team_leader_name'), 'general_maintenance_records', ['team_leader_name'], unique=False)
    op.create_index(op.f('ix_general_maintenance_records_work_site_id'), 'general_maintenance_records', ['work_site_id'], unique=False)
    op.create_table('installation_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('record_number', sa.String(length=20), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.Column('service_type_id', sa.Integer(), nullable=False),
    sa.Column('submitted_by_id', sa.Integer(), nullable=False),
    sa.Column('site_name', sa.String(length=160), nullable=False),
    sa.Column('customer_name', sa.String(length=160), nullable=False),
    sa.Column('site_address', sa.String(length=255), nullable=False),
    sa.Column('service_name', sa.String(length=120), nullable=False),
    sa.Column('team_leader_name', sa.String(length=120), nullable=False),
    sa.Column('equipment_model', sa.String(length=160), nullable=False),
    sa.Column('serial_number', sa.String(length=160), nullable=False),
    sa.Column('warranty_start', sa.Date(), nullable=True),
    sa.Column('result', sa.Enum('completed_successfully', 'completed_with_observations', 'further_action_required', 'unable_to_complete', name='maintenanceresult', native_enum=False, length=40), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('handover_notes', sa.Text(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('length(trim(equipment_model)) > 0', name='ck_installation_equipment_model_present'),
    sa.CheckConstraint('length(trim(notes)) > 0', name='ck_installation_notes_present'),
    sa.CheckConstraint('length(trim(serial_number)) > 0', name='ck_installation_serial_number_present'),
    sa.ForeignKeyConstraint(['service_type_id'], ['service_types.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['submitted_by_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_installation_leader_submitted', 'installation_records', ['submitted_by_id', 'submitted_at'], unique=False)
    op.create_index(op.f('ix_installation_records_record_number'), 'installation_records', ['record_number'], unique=True)
    op.create_index(op.f('ix_installation_records_result'), 'installation_records', ['result'], unique=False)
    op.create_index(op.f('ix_installation_records_serial_number'), 'installation_records', ['serial_number'], unique=False)
    op.create_index(op.f('ix_installation_records_service_type_id'), 'installation_records', ['service_type_id'], unique=False)
    op.create_index(op.f('ix_installation_records_site_id'), 'installation_records', ['site_id'], unique=False)
    op.create_index(op.f('ix_installation_records_submitted_at'), 'installation_records', ['submitted_at'], unique=False)
    op.create_index(op.f('ix_installation_records_submitted_by_id'), 'installation_records', ['submitted_by_id'], unique=False)
    op.create_table('maintenance_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('record_number', sa.String(length=20), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.Column('service_type_id', sa.Integer(), nullable=False),
    sa.Column('submitted_by_id', sa.Integer(), nullable=False),
    sa.Column('site_name', sa.String(length=160), nullable=False),
    sa.Column('customer_name', sa.String(length=160), nullable=False),
    sa.Column('site_address', sa.String(length=255), nullable=False),
    sa.Column('service_name', sa.String(length=120), nullable=False),
    sa.Column('team_leader_name', sa.String(length=120), nullable=False),
    sa.Column('result', sa.Enum('completed_successfully', 'completed_with_observations', 'further_action_required', 'unable_to_complete', name='maintenanceresult', native_enum=False, length=40), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('issue_description', sa.Text(), nullable=True),
    sa.Column('recommendations', sa.Text(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('length(trim(notes)) > 0', name='ck_records_notes_present'),
    sa.ForeignKeyConstraint(['service_type_id'], ['service_types.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['submitted_by_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_maintenance_records_record_number'), 'maintenance_records', ['record_number'], unique=True)
    op.create_index(op.f('ix_maintenance_records_result'), 'maintenance_records', ['result'], unique=False)
    op.create_index(op.f('ix_maintenance_records_service_type_id'), 'maintenance_records', ['service_type_id'], unique=False)
    op.create_index(op.f('ix_maintenance_records_site_id'), 'maintenance_records', ['site_id'], unique=False)
    op.create_index(op.f('ix_maintenance_records_submitted_at'), 'maintenance_records', ['submitted_at'], unique=False)
    op.create_index(op.f('ix_maintenance_records_submitted_by_id'), 'maintenance_records', ['submitted_by_id'], unique=False)
    op.create_index('ix_records_leader_submitted', 'maintenance_records', ['submitted_by_id', 'submitted_at'], unique=False)
    op.create_table('user_auth_states',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('general_maintenance_participants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('record_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.ForeignKeyConstraint(['record_id'], ['general_maintenance_records.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_general_maintenance_participants_record_id'), 'general_maintenance_participants', ['record_id'], unique=False)
    op.create_table('installation_participants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('record_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.CheckConstraint('length(trim(name)) > 0', name='ck_installation_participants_name_present'),
    sa.ForeignKeyConstraint(['record_id'], ['installation_records.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_installation_participants_record_id'), 'installation_participants', ['record_id'], unique=False)
    op.create_table('installation_photos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('record_id', sa.Integer(), nullable=False),
    sa.Column('storage_key', sa.String(length=255), nullable=False),
    sa.Column('thumbnail_key', sa.String(length=255), nullable=True),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('content_type', sa.String(length=60), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['record_id'], ['installation_records.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('storage_key')
    )
    op.create_index(op.f('ix_installation_photos_record_id'), 'installation_photos', ['record_id'], unique=False)
    op.create_table('installation_record_sites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('record_id', sa.Integer(), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.Column('site_name', sa.String(length=120), nullable=False),
    sa.ForeignKeyConstraint(['record_id'], ['installation_records.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['site_id'], ['work_sites.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_installation_record_sites_record_id'), 'installation_record_sites', ['record_id'], unique=True)
    op.create_index(op.f('ix_installation_record_sites_site_id'), 'installation_record_sites', ['site_id'], unique=False)
    op.create_index(op.f('ix_installation_record_sites_site_name'), 'installation_record_sites', ['site_name'], unique=False)
    op.create_table('installed_devices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('installation_record_id', sa.Integer(), nullable=True),
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('customer_name', sa.String(length=160), nullable=False),
    sa.Column('site_name', sa.String(length=160), nullable=False),
    sa.Column('device_name', sa.String(length=120), nullable=False),
    sa.Column('manufacturer', sa.String(length=120), nullable=True),
    sa.Column('device_model', sa.String(length=120), nullable=False),
    sa.Column('serial_number', sa.String(length=160), nullable=False),
    sa.Column('warranty_start', sa.Date(), nullable=True),
    sa.Column('installed_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['device_catalog.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['installation_record_id'], ['installation_records.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_installed_devices_customer_name'), 'installed_devices', ['customer_name'], unique=False)
    op.create_index(op.f('ix_installed_devices_device_id'), 'installed_devices', ['device_id'], unique=False)
    op.create_index(op.f('ix_installed_devices_device_model'), 'installed_devices', ['device_model'], unique=False)
    op.create_index(op.f('ix_installed_devices_device_name'), 'installed_devices', ['device_name'], unique=False)
    op.create_index(op.f('ix_installed_devices_installation_record_id'), 'installed_devices', ['installation_record_id'], unique=True)
    op.create_index(op.f('ix_installed_devices_is_active'), 'installed_devices', ['is_active'], unique=False)
    op.create_index(op.f('ix_installed_devices_serial_number'), 'installed_devices', ['serial_number'], unique=True)
    op.create_index(op.f('ix_installed_devices_site_id'), 'installed_devices', ['site_id'], unique=False)
    op.create_index(op.f('ix_installed_devices_site_name'), 'installed_devices', ['site_name'], unique=False)
    op.create_table('maintenance_participants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('record_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.CheckConstraint('length(trim(name)) > 0', name='ck_participants_name_present'),
    sa.ForeignKeyConstraint(['record_id'], ['maintenance_records.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_maintenance_participants_record_id'), 'maintenance_participants', ['record_id'], unique=False)
    op.create_table('maintenance_photos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('record_id', sa.Integer(), nullable=False),
    sa.Column('storage_key', sa.String(length=255), nullable=False),
    sa.Column('thumbnail_key', sa.String(length=255), nullable=True),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('content_type', sa.String(length=60), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['record_id'], ['maintenance_records.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('storage_key')
    )
    op.create_index(op.f('ix_maintenance_photos_record_id'), 'maintenance_photos', ['record_id'], unique=False)
    op.create_table('maintenance_record_sites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('record_id', sa.Integer(), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.Column('site_name', sa.String(length=120), nullable=False),
    sa.ForeignKeyConstraint(['record_id'], ['maintenance_records.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['site_id'], ['work_sites.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_maintenance_record_sites_record_id'), 'maintenance_record_sites', ['record_id'], unique=True)
    op.create_index(op.f('ix_maintenance_record_sites_site_id'), 'maintenance_record_sites', ['site_id'], unique=False)
    op.create_index(op.f('ix_maintenance_record_sites_site_name'), 'maintenance_record_sites', ['site_name'], unique=False)
    op.create_table('general_maintenance_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('record_id', sa.Integer(), nullable=False),
    sa.Column('installed_device_id', sa.Integer(), nullable=False),
    sa.Column('service_type_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('service_name', sa.String(length=120), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('device_name', sa.String(length=120), nullable=False),
    sa.Column('manufacturer', sa.String(length=120), nullable=True),
    sa.Column('device_model', sa.String(length=120), nullable=False),
    sa.Column('serial_number', sa.String(length=160), nullable=False),
    sa.Column('result', sa.Enum('completed_successfully', 'completed_with_observations', 'further_action_required', 'unable_to_complete', name='maintenanceresult', native_enum=False, length=40), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('issue_description', sa.Text(), nullable=True),
    sa.Column('recommendations', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['device_catalog.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['installed_device_id'], ['installed_devices.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['record_id'], ['general_maintenance_records.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['service_type_id'], ['service_types.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_general_maintenance_items_device_id'), 'general_maintenance_items', ['device_id'], unique=False)
    op.create_index(op.f('ix_general_maintenance_items_device_model'), 'general_maintenance_items', ['device_model'], unique=False)
    op.create_index(op.f('ix_general_maintenance_items_device_name'), 'general_maintenance_items', ['device_name'], unique=False)
    op.create_index(op.f('ix_general_maintenance_items_installed_device_id'), 'general_maintenance_items', ['installed_device_id'], unique=False)
    op.create_index(op.f('ix_general_maintenance_items_record_id'), 'general_maintenance_items', ['record_id'], unique=False)
    op.create_index(op.f('ix_general_maintenance_items_result'), 'general_maintenance_items', ['result'], unique=False)
    op.create_index(op.f('ix_general_maintenance_items_serial_number'), 'general_maintenance_items', ['serial_number'], unique=False)
    op.create_index(op.f('ix_general_maintenance_items_service_name'), 'general_maintenance_items', ['service_name'], unique=False)
    op.create_index(op.f('ix_general_maintenance_items_service_type_id'), 'general_maintenance_items', ['service_type_id'], unique=False)
    op.create_table('installation_record_additional_devices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('record_id', sa.Integer(), nullable=False),
    sa.Column('installed_device_id', sa.Integer(), nullable=False),
    sa.Column('service_type_id', sa.Integer(), nullable=False),
    sa.Column('service_name', sa.String(length=120), nullable=False),
    sa.ForeignKeyConstraint(['installed_device_id'], ['installed_devices.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['record_id'], ['installation_records.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['service_type_id'], ['service_types.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_installation_record_additional_devices_installed_device_id'), 'installation_record_additional_devices', ['installed_device_id'], unique=True)
    op.create_index(op.f('ix_installation_record_additional_devices_record_id'), 'installation_record_additional_devices', ['record_id'], unique=False)
    op.create_index(op.f('ix_installation_record_additional_devices_service_name'), 'installation_record_additional_devices', ['service_name'], unique=False)
    op.create_index(op.f('ix_installation_record_additional_devices_service_type_id'), 'installation_record_additional_devices', ['service_type_id'], unique=False)
    op.create_table('installation_record_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('record_id', sa.Integer(), nullable=False),
    sa.Column('installed_device_id', sa.Integer(), nullable=False),
    sa.Column('service_type_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('service_name', sa.String(length=120), nullable=False),
    sa.Column('device_name', sa.String(length=120), nullable=False),
    sa.Column('manufacturer', sa.String(length=120), nullable=True),
    sa.Column('device_model', sa.String(length=120), nullable=False),
    sa.Column('serial_number', sa.String(length=160), nullable=False),
    sa.Column('warranty_start', sa.Date(), nullable=True),
    sa.Column('result', sa.Enum('completed_successfully', 'completed_with_observations', 'further_action_required', 'unable_to_complete', name='maintenanceresult', native_enum=False, length=40), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('handover_notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['installed_device_id'], ['installed_devices.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['record_id'], ['installation_records.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['service_type_id'], ['service_types.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_installation_record_items_device_model'), 'installation_record_items', ['device_model'], unique=False)
    op.create_index(op.f('ix_installation_record_items_device_name'), 'installation_record_items', ['device_name'], unique=False)
    op.create_index(op.f('ix_installation_record_items_installed_device_id'), 'installation_record_items', ['installed_device_id'], unique=True)
    op.create_index(op.f('ix_installation_record_items_record_id'), 'installation_record_items', ['record_id'], unique=False)
    op.create_index(op.f('ix_installation_record_items_result'), 'installation_record_items', ['result'], unique=False)
    op.create_index(op.f('ix_installation_record_items_serial_number'), 'installation_record_items', ['serial_number'], unique=False)
    op.create_index(op.f('ix_installation_record_items_service_name'), 'installation_record_items', ['service_name'], unique=False)
    op.create_index(op.f('ix_installation_record_items_service_type_id'), 'installation_record_items', ['service_type_id'], unique=False)
    op.create_table('installed_device_sites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('installed_device_id', sa.Integer(), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.Column('site_name', sa.String(length=120), nullable=False),
    sa.ForeignKeyConstraint(['installed_device_id'], ['installed_devices.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['site_id'], ['work_sites.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_installed_device_sites_installed_device_id'), 'installed_device_sites', ['installed_device_id'], unique=True)
    op.create_index(op.f('ix_installed_device_sites_site_id'), 'installed_device_sites', ['site_id'], unique=False)
    op.create_index(op.f('ix_installed_device_sites_site_name'), 'installed_device_sites', ['site_name'], unique=False)
    op.create_table('maintenance_record_additional_devices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('record_id', sa.Integer(), nullable=False),
    sa.Column('installed_device_id', sa.Integer(), nullable=False),
    sa.Column('service_type_id', sa.Integer(), nullable=False),
    sa.Column('service_name', sa.String(length=120), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('device_name', sa.String(length=120), nullable=False),
    sa.Column('manufacturer', sa.String(length=120), nullable=True),
    sa.Column('device_model', sa.String(length=120), nullable=False),
    sa.Column('serial_number', sa.String(length=160), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['device_catalog.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['installed_device_id'], ['installed_devices.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['record_id'], ['maintenance_records.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['service_type_id'], ['service_types.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_maintenance_record_additional_devices_device_id'), 'maintenance_record_additional_devices', ['device_id'], unique=False)
    op.create_index(op.f('ix_maintenance_record_additional_devices_device_model'), 'maintenance_record_additional_devices', ['device_model'], unique=False)
    op.create_index(op.f('ix_maintenance_record_additional_devices_device_name'), 'maintenance_record_additional_devices', ['device_name'], unique=False)
    op.create_index(op.f('ix_maintenance_record_additional_devices_installed_device_id'), 'maintenance_record_additional_devices', ['installed_device_id'], unique=False)
    op.create_index(op.f('ix_maintenance_record_additional_devices_record_id'), 'maintenance_record_additional_devices', ['record_id'], unique=False)
    op.create_index(op.f('ix_maintenance_record_additional_devices_serial_number'), 'maintenance_record_additional_devices', ['serial_number'], unique=False)
    op.create_index(op.f('ix_maintenance_record_additional_devices_service_name'), 'maintenance_record_additional_devices', ['service_name'], unique=False)
    op.create_index(op.f('ix_maintenance_record_additional_devices_service_type_id'), 'maintenance_record_additional_devices', ['service_type_id'], unique=False)
    op.create_table('maintenance_record_devices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('record_id', sa.Integer(), nullable=False),
    sa.Column('installed_device_id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('device_name', sa.String(length=120), nullable=False),
    sa.Column('manufacturer', sa.String(length=120), nullable=True),
    sa.Column('device_model', sa.String(length=120), nullable=False),
    sa.Column('serial_number', sa.String(length=160), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['device_catalog.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['installed_device_id'], ['installed_devices.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['record_id'], ['maintenance_records.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_maintenance_record_devices_device_id'), 'maintenance_record_devices', ['device_id'], unique=False)
    op.create_index(op.f('ix_maintenance_record_devices_device_model'), 'maintenance_record_devices', ['device_model'], unique=False)
    op.create_index(op.f('ix_maintenance_record_devices_device_name'), 'maintenance_record_devices', ['device_name'], unique=False)
    op.create_index(op.f('ix_maintenance_record_devices_installed_device_id'), 'maintenance_record_devices', ['installed_device_id'], unique=False)
    op.create_index(op.f('ix_maintenance_record_devices_record_id'), 'maintenance_record_devices', ['record_id'], unique=True)
    op.create_index(op.f('ix_maintenance_record_devices_serial_number'), 'maintenance_record_devices', ['serial_number'], unique=False)
    op.create_table('maintenance_record_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('record_id', sa.Integer(), nullable=False),
    sa.Column('installed_device_id', sa.Integer(), nullable=False),
    sa.Column('service_type_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('service_name', sa.String(length=120), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('device_name', sa.String(length=120), nullable=False),
    sa.Column('manufacturer', sa.String(length=120), nullable=True),
    sa.Column('device_model', sa.String(length=120), nullable=False),
    sa.Column('serial_number', sa.String(length=160), nullable=False),
    sa.Column('result', sa.Enum('completed_successfully', 'completed_with_observations', 'further_action_required', 'unable_to_complete', name='maintenanceresult', native_enum=False, length=40), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('issue_description', sa.Text(), nullable=True),
    sa.Column('recommendations', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['device_catalog.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['installed_device_id'], ['installed_devices.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['record_id'], ['maintenance_records.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['service_type_id'], ['service_types.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_maintenance_record_items_device_id'), 'maintenance_record_items', ['device_id'], unique=False)
    op.create_index(op.f('ix_maintenance_record_items_device_model'), 'maintenance_record_items', ['device_model'], unique=False)
    op.create_index(op.f('ix_maintenance_record_items_device_name'), 'maintenance_record_items', ['device_name'], unique=False)
    op.create_index(op.f('ix_maintenance_record_items_installed_device_id'), 'maintenance_record_items', ['installed_device_id'], unique=False)
    op.create_index(op.f('ix_maintenance_record_items_record_id'), 'maintenance_record_items', ['record_id'], unique=False)
    op.create_index(op.f('ix_maintenance_record_items_result'), 'maintenance_record_items', ['result'], unique=False)
    op.create_index(op.f('ix_maintenance_record_items_serial_number'), 'maintenance_record_items', ['serial_number'], unique=False)
    op.create_index(op.f('ix_maintenance_record_items_service_name'), 'maintenance_record_items', ['service_name'], unique=False)
    op.create_index(op.f('ix_maintenance_record_items_service_type_id'), 'maintenance_record_items', ['service_type_id'], unique=False)
    op.create_table('general_maintenance_photos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('storage_key', sa.String(length=255), nullable=False),
    sa.Column('thumbnail_key', sa.String(length=255), nullable=True),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('content_type', sa.String(length=60), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['general_maintenance_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('storage_key')
    )
    op.create_index(op.f('ix_general_maintenance_photos_item_id'), 'general_maintenance_photos', ['item_id'], unique=False)
    op.create_table('installation_item_photos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('storage_key', sa.String(length=255), nullable=False),
    sa.Column('thumbnail_key', sa.String(length=255), nullable=True),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('content_type', sa.String(length=60), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['installation_record_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('storage_key')
    )
    op.create_index(op.f('ix_installation_item_photos_item_id'), 'installation_item_photos', ['item_id'], unique=False)
    op.create_table('maintenance_item_photos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('storage_key', sa.String(length=255), nullable=False),
    sa.Column('thumbnail_key', sa.String(length=255), nullable=True),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('content_type', sa.String(length=60), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['maintenance_record_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('storage_key')
    )
    op.create_index(op.f('ix_maintenance_item_photos_item_id'), 'maintenance_item_photos', ['item_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_maintenance_item_photos_item_id'), table_name='maintenance_item_photos')
    op.drop_table('maintenance_item_photos')
    op.drop_index(op.f('ix_installation_item_photos_item_id'), table_name='installation_item_photos')
    op.drop_table('installation_item_photos')
    op.drop_index(op.f('ix_general_maintenance_photos_item_id'), table_name='general_maintenance_photos')
    op.drop_table('general_maintenance_photos')
    op.drop_index(op.f('ix_maintenance_record_items_service_type_id'), table_name='maintenance_record_items')
    op.drop_index(op.f('ix_maintenance_record_items_service_name'), table_name='maintenance_record_items')
    op.drop_index(op.f('ix_maintenance_record_items_serial_number'), table_name='maintenance_record_items')
    op.drop_index(op.f('ix_maintenance_record_items_result'), table_name='maintenance_record_items')
    op.drop_index(op.f('ix_maintenance_record_items_record_id'), table_name='maintenance_record_items')
    op.drop_index(op.f('ix_maintenance_record_items_installed_device_id'), table_name='maintenance_record_items')
    op.drop_index(op.f('ix_maintenance_record_items_device_name'), table_name='maintenance_record_items')
    op.drop_index(op.f('ix_maintenance_record_items_device_model'), table_name='maintenance_record_items')
    op.drop_index(op.f('ix_maintenance_record_items_device_id'), table_name='maintenance_record_items')
    op.drop_table('maintenance_record_items')
    op.drop_index(op.f('ix_maintenance_record_devices_serial_number'), table_name='maintenance_record_devices')
    op.drop_index(op.f('ix_maintenance_record_devices_record_id'), table_name='maintenance_record_devices')
    op.drop_index(op.f('ix_maintenance_record_devices_installed_device_id'), table_name='maintenance_record_devices')
    op.drop_index(op.f('ix_maintenance_record_devices_device_name'), table_name='maintenance_record_devices')
    op.drop_index(op.f('ix_maintenance_record_devices_device_model'), table_name='maintenance_record_devices')
    op.drop_index(op.f('ix_maintenance_record_devices_device_id'), table_name='maintenance_record_devices')
    op.drop_table('maintenance_record_devices')
    op.drop_index(op.f('ix_maintenance_record_additional_devices_service_type_id'), table_name='maintenance_record_additional_devices')
    op.drop_index(op.f('ix_maintenance_record_additional_devices_service_name'), table_name='maintenance_record_additional_devices')
    op.drop_index(op.f('ix_maintenance_record_additional_devices_serial_number'), table_name='maintenance_record_additional_devices')
    op.drop_index(op.f('ix_maintenance_record_additional_devices_record_id'), table_name='maintenance_record_additional_devices')
    op.drop_index(op.f('ix_maintenance_record_additional_devices_installed_device_id'), table_name='maintenance_record_additional_devices')
    op.drop_index(op.f('ix_maintenance_record_additional_devices_device_name'), table_name='maintenance_record_additional_devices')
    op.drop_index(op.f('ix_maintenance_record_additional_devices_device_model'), table_name='maintenance_record_additional_devices')
    op.drop_index(op.f('ix_maintenance_record_additional_devices_device_id'), table_name='maintenance_record_additional_devices')
    op.drop_table('maintenance_record_additional_devices')
    op.drop_index(op.f('ix_installed_device_sites_site_name'), table_name='installed_device_sites')
    op.drop_index(op.f('ix_installed_device_sites_site_id'), table_name='installed_device_sites')
    op.drop_index(op.f('ix_installed_device_sites_installed_device_id'), table_name='installed_device_sites')
    op.drop_table('installed_device_sites')
    op.drop_index(op.f('ix_installation_record_items_service_type_id'), table_name='installation_record_items')
    op.drop_index(op.f('ix_installation_record_items_service_name'), table_name='installation_record_items')
    op.drop_index(op.f('ix_installation_record_items_serial_number'), table_name='installation_record_items')
    op.drop_index(op.f('ix_installation_record_items_result'), table_name='installation_record_items')
    op.drop_index(op.f('ix_installation_record_items_record_id'), table_name='installation_record_items')
    op.drop_index(op.f('ix_installation_record_items_installed_device_id'), table_name='installation_record_items')
    op.drop_index(op.f('ix_installation_record_items_device_name'), table_name='installation_record_items')
    op.drop_index(op.f('ix_installation_record_items_device_model'), table_name='installation_record_items')
    op.drop_table('installation_record_items')
    op.drop_index(op.f('ix_installation_record_additional_devices_service_type_id'), table_name='installation_record_additional_devices')
    op.drop_index(op.f('ix_installation_record_additional_devices_service_name'), table_name='installation_record_additional_devices')
    op.drop_index(op.f('ix_installation_record_additional_devices_record_id'), table_name='installation_record_additional_devices')
    op.drop_index(op.f('ix_installation_record_additional_devices_installed_device_id'), table_name='installation_record_additional_devices')
    op.drop_table('installation_record_additional_devices')
    op.drop_index(op.f('ix_general_maintenance_items_service_type_id'), table_name='general_maintenance_items')
    op.drop_index(op.f('ix_general_maintenance_items_service_name'), table_name='general_maintenance_items')
    op.drop_index(op.f('ix_general_maintenance_items_serial_number'), table_name='general_maintenance_items')
    op.drop_index(op.f('ix_general_maintenance_items_result'), table_name='general_maintenance_items')
    op.drop_index(op.f('ix_general_maintenance_items_record_id'), table_name='general_maintenance_items')
    op.drop_index(op.f('ix_general_maintenance_items_installed_device_id'), table_name='general_maintenance_items')
    op.drop_index(op.f('ix_general_maintenance_items_device_name'), table_name='general_maintenance_items')
    op.drop_index(op.f('ix_general_maintenance_items_device_model'), table_name='general_maintenance_items')
    op.drop_index(op.f('ix_general_maintenance_items_device_id'), table_name='general_maintenance_items')
    op.drop_table('general_maintenance_items')
    op.drop_index(op.f('ix_maintenance_record_sites_site_name'), table_name='maintenance_record_sites')
    op.drop_index(op.f('ix_maintenance_record_sites_site_id'), table_name='maintenance_record_sites')
    op.drop_index(op.f('ix_maintenance_record_sites_record_id'), table_name='maintenance_record_sites')
    op.drop_table('maintenance_record_sites')
    op.drop_index(op.f('ix_maintenance_photos_record_id'), table_name='maintenance_photos')
    op.drop_table('maintenance_photos')
    op.drop_index(op.f('ix_maintenance_participants_record_id'), table_name='maintenance_participants')
    op.drop_table('maintenance_participants')
    op.drop_index(op.f('ix_installed_devices_site_name'), table_name='installed_devices')
    op.drop_index(op.f('ix_installed_devices_site_id'), table_name='installed_devices')
    op.drop_index(op.f('ix_installed_devices_serial_number'), table_name='installed_devices')
    op.drop_index(op.f('ix_installed_devices_is_active'), table_name='installed_devices')
    op.drop_index(op.f('ix_installed_devices_installation_record_id'), table_name='installed_devices')
    op.drop_index(op.f('ix_installed_devices_device_name'), table_name='installed_devices')
    op.drop_index(op.f('ix_installed_devices_device_model'), table_name='installed_devices')
    op.drop_index(op.f('ix_installed_devices_device_id'), table_name='installed_devices')
    op.drop_index(op.f('ix_installed_devices_customer_name'), table_name='installed_devices')
    op.drop_table('installed_devices')
    op.drop_index(op.f('ix_installation_record_sites_site_name'), table_name='installation_record_sites')
    op.drop_index(op.f('ix_installation_record_sites_site_id'), table_name='installation_record_sites')
    op.drop_index(op.f('ix_installation_record_sites_record_id'), table_name='installation_record_sites')
    op.drop_table('installation_record_sites')
    op.drop_index(op.f('ix_installation_photos_record_id'), table_name='installation_photos')
    op.drop_table('installation_photos')
    op.drop_index(op.f('ix_installation_participants_record_id'), table_name='installation_participants')
    op.drop_table('installation_participants')
    op.drop_index(op.f('ix_general_maintenance_participants_record_id'), table_name='general_maintenance_participants')
    op.drop_table('general_maintenance_participants')
    op.drop_table('user_auth_states')
    op.drop_index('ix_records_leader_submitted', table_name='maintenance_records')
    op.drop_index(op.f('ix_maintenance_records_submitted_by_id'), table_name='maintenance_records')
    op.drop_index(op.f('ix_maintenance_records_submitted_at'), table_name='maintenance_records')
    op.drop_index(op.f('ix_maintenance_records_site_id'), table_name='maintenance_records')
    op.drop_index(op.f('ix_maintenance_records_service_type_id'), table_name='maintenance_records')
    op.drop_index(op.f('ix_maintenance_records_result'), table_name='maintenance_records')
    op.drop_index(op.f('ix_maintenance_records_record_number'), table_name='maintenance_records')
    op.drop_table('maintenance_records')
    op.drop_index(op.f('ix_installation_records_submitted_by_id'), table_name='installation_records')
    op.drop_index(op.f('ix_installation_records_submitted_at'), table_name='installation_records')
    op.drop_index(op.f('ix_installation_records_site_id'), table_name='installation_records')
    op.drop_index(op.f('ix_installation_records_service_type_id'), table_name='installation_records')
    op.drop_index(op.f('ix_installation_records_serial_number'), table_name='installation_records')
    op.drop_index(op.f('ix_installation_records_result'), table_name='installation_records')
    op.drop_index(op.f('ix_installation_records_record_number'), table_name='installation_records')
    op.drop_index('ix_installation_leader_submitted', table_name='installation_records')
    op.drop_table('installation_records')
    op.drop_index(op.f('ix_general_maintenance_records_work_site_id'), table_name='general_maintenance_records')
    op.drop_index(op.f('ix_general_maintenance_records_team_leader_name'), table_name='general_maintenance_records')
    op.drop_index(op.f('ix_general_maintenance_records_submitted_by_id'), table_name='general_maintenance_records')
    op.drop_index(op.f('ix_general_maintenance_records_submitted_at'), table_name='general_maintenance_records')
    op.drop_index(op.f('ix_general_maintenance_records_site_name'), table_name='general_maintenance_records')
    op.drop_index(op.f('ix_general_maintenance_records_site_id'), table_name='general_maintenance_records')
    op.drop_index(op.f('ix_general_maintenance_records_service_type_id'), table_name='general_maintenance_records')
    op.drop_index(op.f('ix_general_maintenance_records_service_name'), table_name='general_maintenance_records')
    op.drop_index(op.f('ix_general_maintenance_records_result'), table_name='general_maintenance_records')
    op.drop_index(op.f('ix_general_maintenance_records_record_number'), table_name='general_maintenance_records')
    op.drop_index(op.f('ix_general_maintenance_records_project_name'), table_name='general_maintenance_records')
    op.drop_table('general_maintenance_records')
    op.drop_index(op.f('ix_customer_project_assignments_user_id'), table_name='customer_project_assignments')
    op.drop_index(op.f('ix_customer_project_assignments_project_id'), table_name='customer_project_assignments')
    op.drop_table('customer_project_assignments')
    op.drop_index(op.f('ix_admin_recovery_contacts_email'), table_name='admin_recovery_contacts')
    op.drop_table('admin_recovery_contacts')
    op.drop_index(op.f('ix_account_recovery_tokens_user_id'), table_name='account_recovery_tokens')
    op.drop_index(op.f('ix_account_recovery_tokens_used_at'), table_name='account_recovery_tokens')
    op.drop_index(op.f('ix_account_recovery_tokens_token_hash'), table_name='account_recovery_tokens')
    op.drop_index(op.f('ix_account_recovery_tokens_purpose'), table_name='account_recovery_tokens')
    op.drop_index(op.f('ix_account_recovery_tokens_expires_at'), table_name='account_recovery_tokens')
    op.drop_index(op.f('ix_account_recovery_tokens_created_at'), table_name='account_recovery_tokens')
    op.drop_table('account_recovery_tokens')
    op.drop_index(op.f('ix_work_sites_name'), table_name='work_sites')
    op.drop_index(op.f('ix_work_sites_is_active'), table_name='work_sites')
    op.drop_table('work_sites')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_is_active'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_sites_name'), table_name='sites')
    op.drop_index(op.f('ix_sites_is_active'), table_name='sites')
    op.drop_index(op.f('ix_sites_customer_name'), table_name='sites')
    op.drop_table('sites')
    op.drop_index(op.f('ix_service_types_name'), table_name='service_types')
    op.drop_index(op.f('ix_service_types_is_active'), table_name='service_types')
    op.drop_table('service_types')
    op.drop_index(op.f('ix_record_revisions_record_type'), table_name='record_revisions')
    op.drop_index(op.f('ix_record_revisions_record_number'), table_name='record_revisions')
    op.drop_index(op.f('ix_record_revisions_record_id'), table_name='record_revisions')
    op.drop_index(op.f('ix_record_revisions_edited_by_id'), table_name='record_revisions')
    op.drop_index(op.f('ix_record_revisions_created_at'), table_name='record_revisions')
    op.drop_index(op.f('ix_record_revisions_action'), table_name='record_revisions')
    op.drop_table('record_revisions')
    op.drop_table('record_counters')
    op.drop_table('installation_record_counters')
    op.drop_table('general_maintenance_record_counters')
    op.drop_index(op.f('ix_device_catalog_name'), table_name='device_catalog')
    op.drop_index(op.f('ix_device_catalog_model'), table_name='device_catalog')
    op.drop_index(op.f('ix_device_catalog_manufacturer'), table_name='device_catalog')
    op.drop_index(op.f('ix_device_catalog_is_active'), table_name='device_catalog')
    op.drop_table('device_catalog')
    op.drop_index(op.f('ix_account_recovery_attempts_ip_hash'), table_name='account_recovery_attempts')
    op.drop_index(op.f('ix_account_recovery_attempts_identifier_hash'), table_name='account_recovery_attempts')
    op.drop_index(op.f('ix_account_recovery_attempts_created_at'), table_name='account_recovery_attempts')
    op.drop_table('account_recovery_attempts')
    # ### end Alembic commands ###
