"""PDF and Excel exports for the Administrator Logs Report."""
from __future__ import annotations

import io
import json
from datetime import datetime
from typing import Iterable

from openpyxl import Workbook
from openpyxl.styles import Alignment, Font, PatternFill
from openpyxl.utils import get_column_letter
from reportlab.lib import colors
from reportlab.lib.pagesizes import A4, landscape
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import mm
from reportlab.platypus import Paragraph, SimpleDocTemplate, Spacer, Table, TableStyle

from .config import settings
from .models import AuditEvent
from .pdf_text import pdf_text, style_for_pdf_text


NAVY = "17324D"
TEAL = "138B8E"
RED = "B42318"


def _displayed(value: datetime) -> str:
    return f"{value + settings.display_tz_offset:%Y-%m-%d %H:%M:%S} {settings.display_tz_label}"


def _changes(event: AuditEvent) -> str:
    return json.dumps(event.changes, ensure_ascii=False, default=str, sort_keys=True) if event.changes else ""


def _safe_excel_text(value: object) -> str:
    text = "" if value is None else str(value)
    return f"'{text}" if text.startswith(("=", "+", "-", "@")) else text


def build_logs_report_xlsx(events: Iterable[AuditEvent], filters: dict[str, str], generated_by: str) -> bytes:
    rows = list(events)
    workbook = Workbook()
    sheet = workbook.active
    sheet.title = "Logs Report"
    sheet.sheet_view.showGridLines = False
    sheet.merge_cells("A1:L1")
    sheet["A1"] = "Service Management System — Logs Report"
    sheet["A1"].font = Font(size=16, bold=True, color="FFFFFF")
    sheet["A1"].fill = PatternFill("solid", fgColor=NAVY)
    sheet["A1"].alignment = Alignment(horizontal="center", vertical="center")
    sheet.row_dimensions[1].height = 30
    sheet.merge_cells("A2:L2")
    sheet["A2"] = f"Generated by {generated_by} | {len(rows)} matching events"
    sheet["A2"].font = Font(color="526575", italic=True)
    sheet["A2"].alignment = Alignment(horizontal="center")
    headers = ["Date & Time", "User", "Role", "Action", "Module", "Record Type", "Record ID", "Record / Entity", "Request", "Result", "IP Address", "Recorded Changes"]
    for column, header in enumerate(headers, 1):
        cell = sheet.cell(row=4, column=column, value=header)
        cell.font = Font(bold=True, color="FFFFFF")
        cell.fill = PatternFill("solid", fgColor=TEAL)
        cell.alignment = Alignment(horizontal="center", vertical="center")
    for row_index, event in enumerate(rows, 5):
        values = [
            _displayed(event.created_at), event.actor_name, event.actor_role or "",
            event.action.replace("_", " ").title(), event.module.replace("_", " ").title(),
            (event.entity_type or "").replace("_", " ").title(), event.entity_id or "",
            event.entity_label or "", f"{event.method} {event.path}",
            f"{'Successful' if event.status_code < 400 else 'Failed'} ({event.status_code})",
            event.ip_address or "", _changes(event),
        ]
        for column, value in enumerate(values, 1):
            cell = sheet.cell(row=row_index, column=column, value=_safe_excel_text(value))
            cell.alignment = Alignment(vertical="top", wrap_text=True)
            if row_index % 2:
                cell.fill = PatternFill("solid", fgColor="F4F7F9")
        sheet.cell(row=row_index, column=10).font = Font(color="16794A" if event.status_code < 400 else RED, bold=True)
    sheet.freeze_panes = "A5"
    sheet.auto_filter.ref = f"A4:L{max(4, len(rows) + 4)}"
    for column, width in enumerate([24, 24, 16, 22, 22, 22, 16, 30, 40, 20, 20, 70], 1):
        sheet.column_dimensions[get_column_letter(column)].width = width
    sheet.sheet_properties.pageSetUpPr.fitToPage = True
    sheet.page_setup.fitToWidth = 1
    sheet.page_setup.fitToHeight = 0
    output = io.BytesIO()
    workbook.save(output)
    return output.getvalue()


def build_logs_report_pdf(events: Iterable[AuditEvent], filters: dict[str, str], generated_by: str) -> bytes:
    rows = list(events)
    output = io.BytesIO()
    document = SimpleDocTemplate(output, pagesize=landscape(A4), leftMargin=12 * mm, rightMargin=12 * mm, topMargin=12 * mm, bottomMargin=12 * mm, title="Logs Report")
    styles = getSampleStyleSheet()
    title = ParagraphStyle("LogsTitle", parent=styles["Title"], fontName="Helvetica-Bold", fontSize=20, leading=24, textColor=colors.HexColor(f"#{NAVY}"), spaceAfter=4 * mm)
    body = ParagraphStyle("LogsBody", parent=styles["BodyText"], fontName="Helvetica", fontSize=6.5, leading=8, textColor=colors.HexColor(f"#{NAVY}"))
    header = ParagraphStyle("LogsHeader", parent=body, fontName="Helvetica-Bold", textColor=colors.white)

    def paragraph(value: object, style: ParagraphStyle = body) -> Paragraph:
        return Paragraph(pdf_text(value), style_for_pdf_text(value, style))

    story = [paragraph("Logs Report", title), paragraph(f"Generated by {generated_by} | {len(rows)} matching events | {datetime.utcnow():%Y-%m-%d %H:%M:%S} UTC"), Spacer(1, 4 * mm)]
    table_rows = [[paragraph("Date & Time", header), paragraph("User", header), paragraph("Action", header), paragraph("Module", header), paragraph("Record / Entity", header), paragraph("Result", header), paragraph("IP Address", header), paragraph("Details", header)]]
    for event in rows:
        table_rows.append([
            paragraph(_displayed(event.created_at)), paragraph(f"{event.actor_name}\n{event.actor_role or ''}"),
            paragraph(event.action.replace("_", " ").title()), paragraph(event.module.replace("_", " ").title()),
            paragraph(event.entity_label or event.entity_type or event.entity_id or "-"),
            paragraph(f"{'Successful' if event.status_code < 400 else 'Failed'} ({event.status_code})"),
            paragraph(event.ip_address or "-"), paragraph(f"{event.method} {event.path}\n{_changes(event)}"),
        ])
    table = Table(table_rows, colWidths=[31 * mm, 29 * mm, 25 * mm, 25 * mm, 34 * mm, 23 * mm, 26 * mm, 70 * mm], repeatRows=1, hAlign="LEFT")
    table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor(f"#{NAVY}")),
        ("GRID", (0, 0), (-1, -1), 0.35, colors.HexColor("#D7E0E6")),
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#F4F7F9")]),
        ("LEFTPADDING", (0, 0), (-1, -1), 4), ("RIGHTPADDING", (0, 0), (-1, -1), 4),
        ("TOPPADDING", (0, 0), (-1, -1), 4), ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
    ]))
    story.append(table)
    document.build(story)
    return output.getvalue()


def build_technician_activity_xlsx(audit: dict, generated_by: str) -> bytes:
    """Create a readable workbook for the filtered technician ledger."""
    workbook = Workbook()
    summary_sheet = workbook.active
    summary_sheet.title = "Summary"
    summary_sheet.sheet_view.showGridLines = False
    summary_sheet.merge_cells("A1:F1")
    summary_sheet["A1"] = f"Technician Activity — {audit['technician'].full_name}"
    summary_sheet["A1"].font = Font(size=16, bold=True, color="FFFFFF")
    summary_sheet["A1"].fill = PatternFill("solid", fgColor=NAVY)
    summary_sheet["A1"].alignment = Alignment(horizontal="center")
    summary_sheet["A2"] = f"Generated by {generated_by}"
    metrics = [
        ("Total visits", audit["summary"]["total_visits"]),
        ("Visits led", audit["summary"]["led_visits"]),
        ("Visits assisted", audit["summary"]["assisted_visits"]),
        ("Devices / services", audit["summary"]["total_devices"]),
        ("Evidence photos", audit["summary"]["total_photos"]),
        ("Record edits", audit["summary"]["total_edits"]),
    ]
    for index, (label, value) in enumerate(metrics, 4):
        summary_sheet.cell(index, 1, label).font = Font(bold=True, color=NAVY)
        summary_sheet.cell(index, 2, value)
    summary_sheet.column_dimensions["A"].width = 28
    summary_sheet.column_dimensions["B"].width = 18

    history = workbook.create_sheet("Work History")
    history.sheet_view.showGridLines = False
    headers = ["Date & Time", "Role", "Record ID", "Record Type", "Project / Customer", "Site", "Result", "Devices / Services", "Photos"]
    history.append(headers)
    for cell in history[1]:
        cell.font = Font(bold=True, color="FFFFFF")
        cell.fill = PatternFill("solid", fgColor=TEAL)
        cell.alignment = Alignment(horizontal="center")
    for record in audit["records"]:
        history.append([
            _displayed(record["submitted_at"]), record["technician_role"], record["record_number"],
            record["record_type"], record["customer_name"], record["work_site_name"] or record["site_name"],
            record["result"].label, record["device_count"], record["photo_count"],
        ])
    history.freeze_panes = "A2"
    history.auto_filter.ref = f"A1:I{max(1, history.max_row)}"
    for column, width in enumerate([24, 14, 22, 24, 30, 28, 28, 20, 12], 1):
        history.column_dimensions[get_column_letter(column)].width = width

    edits = workbook.create_sheet("Edit History")
    edits.sheet_view.showGridLines = False
    edit_headers = ["Date & Time", "Action", "Record ID", "Record Type", "Changed Fields"]
    edits.append(edit_headers)
    for cell in edits[1]:
        cell.font = Font(bold=True, color="FFFFFF")
        cell.fill = PatternFill("solid", fgColor=TEAL)
        cell.alignment = Alignment(horizontal="center")
    for revision in audit["revisions"]:
        edits.append([
            _displayed(revision.created_at), revision.action.title(), revision.record_number,
            revision.record_type.replace("_", " ").title(),
            ", ".join(key.replace("_", " ").title() for key in revision.changes),
        ])
    edits.freeze_panes = "A2"
    edits.auto_filter.ref = f"A1:E{max(1, edits.max_row)}"
    for column, width in enumerate([24, 18, 22, 28, 70], 1):
        edits.column_dimensions[get_column_letter(column)].width = width

    for sheet in (history, edits):
        for row in sheet.iter_rows(min_row=2):
            for cell in row:
                cell.alignment = Alignment(vertical="top", wrap_text=True)
                if cell.row % 2:
                    cell.fill = PatternFill("solid", fgColor="F4F7F9")
    output = io.BytesIO()
    workbook.save(output)
    return output.getvalue()
